site_name: CIS-CAT Pro Assessor v4
nav:
   - Home: index.md
        - SecureSuite License: SecureSuite License.md
        - Configuration Guide: Configuration Guide.md
        - User Guide: User Guide for CLI.md
        - CIS Benchmark Support: Coverage Guide.md 
        - Quick Start: Quick Start Guides.md
        - Control Assessment User Guide: User Guide for Controls Assessment Module.md
        - Third Party Licenses: License Information.md
        - Change Log: Change Log.md
 
theme:
  name: readthedocs