site_name: CIS-CAT Pro Assessor v4

nav:
    - Home: index.md
    - Source:
        - User Guide for CLI: User Guide for CLI.md
        - User Guide for Assesor Service: User Guide for Assessor Service.md
        - User Guide for Controls Assessment Module: User Guide for Controls Assessment Module.md
        - Configuration Guide: Configuration Guide.md
        - Coverage Guide: Coverage Guide.md
        - 3rd-Party Licenses: License Information.md
        - Change Log: Change Log.md

theme:
  name: readthedocs